version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-dom
    versions:
    - 16.14.0
  - dependency-name: react-scripts
    versions:
    - 4.0.3
